export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST';
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS';
export const REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL';

export const REVIEW_ONE_REQUEST = 'REVIEW_ONE_REQUEST';
export const REVIEW_ONE_SUCCESS = 'REVIEW_ONE_SUCCESS';
export const REVIEW_ONE_FAIL = 'REVIEW_ONE_FAIL';

export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST'
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS'
export const REVIEW_CREATE_FAIL = 'REVIEW_CREATE_FAIL'
